##
## EPITECH PROJECT, 2023
## make
## File description:
## make
##

all:
	make -C snake/
	make -C nibbler/
	make -C menu/
	make -C user/


clean:
	make clean -C snake/
	make clean -C nibbler/
	make clean -C menu/
	make clean -C user/

fclean: clean
	make fclean -C snake/
	make fclean -C nibbler/
	make fclean -C menu/
	make fclean -C user/

re:	fclean all
